/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kaplan.kafka.demo.kafka.avro.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateContactEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 920094030303071111L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateContactEvent\",\"namespace\":\"com.kaplan.kafka.demo.kafka.avro.domain\",\"fields\":[{\"name\":\"commitId\",\"type\":\"string\"},{\"name\":\"contact\",\"type\":{\"type\":\"record\",\"name\":\"ContactAvro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"contactName\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateContactEvent> ENCODER =
      new BinaryMessageEncoder<CreateContactEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateContactEvent> DECODER =
      new BinaryMessageDecoder<CreateContactEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateContactEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateContactEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateContactEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateContactEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateContactEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateContactEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateContactEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateContactEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence commitId;
  @Deprecated public com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro contact;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateContactEvent() {}

  /**
   * All-args constructor.
   * @param commitId The new value for commitId
   * @param contact The new value for contact
   */
  public CreateContactEvent(java.lang.CharSequence commitId, com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro contact) {
    this.commitId = commitId;
    this.contact = contact;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return commitId;
    case 1: return contact;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: commitId = (java.lang.CharSequence)value$; break;
    case 1: contact = (com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'commitId' field.
   * @return The value of the 'commitId' field.
   */
  public java.lang.CharSequence getCommitId() {
    return commitId;
  }


  /**
   * Sets the value of the 'commitId' field.
   * @param value the value to set.
   */
  public void setCommitId(java.lang.CharSequence value) {
    this.commitId = value;
  }

  /**
   * Gets the value of the 'contact' field.
   * @return The value of the 'contact' field.
   */
  public com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro getContact() {
    return contact;
  }


  /**
   * Sets the value of the 'contact' field.
   * @param value the value to set.
   */
  public void setContact(com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro value) {
    this.contact = value;
  }

  /**
   * Creates a new CreateContactEvent RecordBuilder.
   * @return A new CreateContactEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder newBuilder() {
    return new com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder();
  }

  /**
   * Creates a new CreateContactEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateContactEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder newBuilder(com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder other) {
    if (other == null) {
      return new com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder();
    } else {
      return new com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder(other);
    }
  }

  /**
   * Creates a new CreateContactEvent RecordBuilder by copying an existing CreateContactEvent instance.
   * @param other The existing instance to copy.
   * @return A new CreateContactEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder newBuilder(com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent other) {
    if (other == null) {
      return new com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder();
    } else {
      return new com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateContactEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateContactEvent>
    implements org.apache.avro.data.RecordBuilder<CreateContactEvent> {

    private java.lang.CharSequence commitId;
    private com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro contact;
    private com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.Builder contactBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.commitId)) {
        this.commitId = data().deepCopy(fields()[0].schema(), other.commitId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.contact)) {
        this.contact = data().deepCopy(fields()[1].schema(), other.contact);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (other.hasContactBuilder()) {
        this.contactBuilder = com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.newBuilder(other.getContactBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing CreateContactEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.commitId)) {
        this.commitId = data().deepCopy(fields()[0].schema(), other.commitId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contact)) {
        this.contact = data().deepCopy(fields()[1].schema(), other.contact);
        fieldSetFlags()[1] = true;
      }
      this.contactBuilder = null;
    }

    /**
      * Gets the value of the 'commitId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommitId() {
      return commitId;
    }


    /**
      * Sets the value of the 'commitId' field.
      * @param value The value of 'commitId'.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder setCommitId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.commitId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'commitId' field has been set.
      * @return True if the 'commitId' field has been set, false otherwise.
      */
    public boolean hasCommitId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'commitId' field.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder clearCommitId() {
      commitId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contact' field.
      * @return The value.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro getContact() {
      return contact;
    }


    /**
      * Sets the value of the 'contact' field.
      * @param value The value of 'contact'.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder setContact(com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro value) {
      validate(fields()[1], value);
      this.contactBuilder = null;
      this.contact = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contact' field has been set.
      * @return True if the 'contact' field has been set, false otherwise.
      */
    public boolean hasContact() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'contact' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.Builder getContactBuilder() {
      if (contactBuilder == null) {
        if (hasContact()) {
          setContactBuilder(com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.newBuilder(contact));
        } else {
          setContactBuilder(com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.newBuilder());
        }
      }
      return contactBuilder;
    }

    /**
     * Sets the Builder instance for the 'contact' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder setContactBuilder(com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro.Builder value) {
      clearContact();
      contactBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'contact' field has an active Builder instance
     * @return True if the 'contact' field has an active Builder instance
     */
    public boolean hasContactBuilder() {
      return contactBuilder != null;
    }

    /**
      * Clears the value of the 'contact' field.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.CreateContactEvent.Builder clearContact() {
      contact = null;
      contactBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateContactEvent build() {
      try {
        CreateContactEvent record = new CreateContactEvent();
        record.commitId = fieldSetFlags()[0] ? this.commitId : (java.lang.CharSequence) defaultValue(fields()[0]);
        if (contactBuilder != null) {
          try {
            record.contact = this.contactBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("contact"));
            throw e;
          }
        } else {
          record.contact = fieldSetFlags()[1] ? this.contact : (com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro) defaultValue(fields()[1]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateContactEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateContactEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateContactEvent>
    READER$ = (org.apache.avro.io.DatumReader<CreateContactEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.commitId);

    this.contact.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.commitId = in.readString(this.commitId instanceof Utf8 ? (Utf8)this.commitId : null);

      if (this.contact == null) {
        this.contact = new com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro();
      }
      this.contact.customDecode(in);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.commitId = in.readString(this.commitId instanceof Utf8 ? (Utf8)this.commitId : null);
          break;

        case 1:
          if (this.contact == null) {
            this.contact = new com.kaplan.kafka.demo.kafka.avro.domain.ContactAvro();
          }
          this.contact.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










