/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kaplan.kafka.demo.kafka.avro.domain;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NavisionContactCreateEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5799832659324823747L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NavisionContactCreateEvent\",\"namespace\":\"com.kaplan.kafka.demo.kafka.avro.domain\",\"fields\":[{\"name\":\"commitId\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NavisionContactCreateEvent> ENCODER =
      new BinaryMessageEncoder<NavisionContactCreateEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NavisionContactCreateEvent> DECODER =
      new BinaryMessageDecoder<NavisionContactCreateEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NavisionContactCreateEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NavisionContactCreateEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NavisionContactCreateEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<NavisionContactCreateEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NavisionContactCreateEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NavisionContactCreateEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NavisionContactCreateEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NavisionContactCreateEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence commitId;
  @Deprecated public java.lang.CharSequence name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NavisionContactCreateEvent() {}

  /**
   * All-args constructor.
   * @param commitId The new value for commitId
   * @param name The new value for name
   */
  public NavisionContactCreateEvent(java.lang.CharSequence commitId, java.lang.CharSequence name) {
    this.commitId = commitId;
    this.name = name;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return commitId;
    case 1: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: commitId = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'commitId' field.
   * @return The value of the 'commitId' field.
   */
  public java.lang.CharSequence getCommitId() {
    return commitId;
  }


  /**
   * Sets the value of the 'commitId' field.
   * @param value the value to set.
   */
  public void setCommitId(java.lang.CharSequence value) {
    this.commitId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Creates a new NavisionContactCreateEvent RecordBuilder.
   * @return A new NavisionContactCreateEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder newBuilder() {
    return new com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder();
  }

  /**
   * Creates a new NavisionContactCreateEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NavisionContactCreateEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder newBuilder(com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder other) {
    if (other == null) {
      return new com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder();
    } else {
      return new com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder(other);
    }
  }

  /**
   * Creates a new NavisionContactCreateEvent RecordBuilder by copying an existing NavisionContactCreateEvent instance.
   * @param other The existing instance to copy.
   * @return A new NavisionContactCreateEvent RecordBuilder
   */
  public static com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder newBuilder(com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent other) {
    if (other == null) {
      return new com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder();
    } else {
      return new com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for NavisionContactCreateEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NavisionContactCreateEvent>
    implements org.apache.avro.data.RecordBuilder<NavisionContactCreateEvent> {

    private java.lang.CharSequence commitId;
    private java.lang.CharSequence name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.commitId)) {
        this.commitId = data().deepCopy(fields()[0].schema(), other.commitId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing NavisionContactCreateEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.commitId)) {
        this.commitId = data().deepCopy(fields()[0].schema(), other.commitId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'commitId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCommitId() {
      return commitId;
    }


    /**
      * Sets the value of the 'commitId' field.
      * @param value The value of 'commitId'.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder setCommitId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.commitId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'commitId' field has been set.
      * @return True if the 'commitId' field has been set, false otherwise.
      */
    public boolean hasCommitId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'commitId' field.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder clearCommitId() {
      commitId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.kaplan.kafka.demo.kafka.avro.domain.NavisionContactCreateEvent.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NavisionContactCreateEvent build() {
      try {
        NavisionContactCreateEvent record = new NavisionContactCreateEvent();
        record.commitId = fieldSetFlags()[0] ? this.commitId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NavisionContactCreateEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<NavisionContactCreateEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NavisionContactCreateEvent>
    READER$ = (org.apache.avro.io.DatumReader<NavisionContactCreateEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.commitId);

    out.writeString(this.name);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.commitId = in.readString(this.commitId instanceof Utf8 ? (Utf8)this.commitId : null);

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.commitId = in.readString(this.commitId instanceof Utf8 ? (Utf8)this.commitId : null);
          break;

        case 1:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










